/**
 * The house collection: a hand-written set of reliable dinners, tagged by
 * cooking category so weather-aware suggestions work out of the box —
 * including before a Spoonacular key is configured.
 */

export const HOUSE_RECIPES = [
  {
    id: 'house-tomato-soup',
    title: 'Roasted Tomato Soup with Cheddar Toast',
    categories: ['soup', 'baked'],
    cuisine: 'American',
    diets: ['vegetarian'],
    readyInMinutes: 50,
    servings: 4,
    summary: 'Deeply roasted tomatoes and garlic blended silky, with a broiled cheddar toast for dunking.',
    ingredients: [
      { name: 'ripe tomatoes', amount: 2, unit: 'lb' },
      { name: 'garlic cloves', amount: 6, unit: '' },
      { name: 'yellow onion', amount: 1, unit: '' },
      { name: 'olive oil', amount: 3, unit: 'tbsp' },
      { name: 'vegetable stock', amount: 2, unit: 'cups' },
      { name: 'heavy cream', amount: 0.33, unit: 'cup' },
      { name: 'sourdough bread', amount: 4, unit: 'slices' },
      { name: 'sharp cheddar', amount: 4, unit: 'oz' },
    ],
    steps: [
      'Halve the tomatoes and toss with the onion (quartered), garlic, olive oil, and a big pinch of salt on a sheet pan.',
      'Roast at 425°F (220°C) for 30–35 minutes until charred at the edges.',
      'Blend the roasted vegetables with the stock until smooth; warm in a pot and stir in the cream. Season.',
      'Broil the bread topped with cheddar until bubbling, and serve alongside.',
    ],
  },
  {
    id: 'house-chicken-stew',
    title: 'Braised Chicken Thighs with White Beans & Kale',
    categories: ['braise', 'stew'],
    cuisine: 'French',
    diets: [],
    readyInMinutes: 55,
    servings: 4,
    summary: 'One-pot bone-in thighs braised with white beans, finished with lemon and wilted kale.',
    ingredients: [
      { name: 'bone-in chicken thighs', amount: 8, unit: '' },
      { name: 'cannellini beans (cans)', amount: 2, unit: '' },
      { name: 'lacinato kale', amount: 1, unit: 'bunch' },
      { name: 'chicken stock', amount: 2, unit: 'cups' },
      { name: 'garlic cloves', amount: 4, unit: '' },
      { name: 'lemon', amount: 1, unit: '' },
      { name: 'olive oil', amount: 2, unit: 'tbsp' },
    ],
    steps: [
      'Season the thighs well and brown skin-side down in olive oil, 7–8 minutes; set aside.',
      'Soften the garlic in the fat, add the drained beans and stock, and nestle the chicken back in.',
      'Braise, partly covered, 30 minutes at a gentle simmer.',
      'Stir in torn kale to wilt, squeeze in the lemon, and serve in shallow bowls.',
    ],
  },
  {
    id: 'house-beef-chili',
    title: 'Stovetop Beef & Black Bean Chili',
    categories: ['stew', 'soup'],
    cuisine: 'Tex-Mex',
    diets: [],
    readyInMinutes: 60,
    servings: 6,
    summary: 'A weeknight-scale chili with real depth: toasted spices, black beans, and a square of dark chocolate.',
    ingredients: [
      { name: 'ground beef', amount: 1.5, unit: 'lb' },
      { name: 'black beans (cans)', amount: 2, unit: '' },
      { name: 'crushed tomatoes', amount: 28, unit: 'oz' },
      { name: 'yellow onion', amount: 1, unit: '' },
      { name: 'chili powder', amount: 3, unit: 'tbsp' },
      { name: 'ground cumin', amount: 1, unit: 'tbsp' },
      { name: 'dark chocolate', amount: 1, unit: 'square' },
      { name: 'sour cream', amount: 0.5, unit: 'cup' },
    ],
    steps: [
      'Brown the beef hard in a Dutch oven; push aside and soften the diced onion.',
      'Toast the chili powder and cumin in the fat for 30 seconds.',
      'Add tomatoes, drained beans, a cup of water, and the chocolate. Simmer 40 minutes.',
      'Season, then serve with sour cream and whatever crunchy things are around.',
    ],
  },
  {
    id: 'house-mushroom-ragu',
    title: 'Mushroom Ragù over Polenta',
    categories: ['braise', 'pasta'],
    cuisine: 'Italian',
    diets: ['vegetarian'],
    readyInMinutes: 45,
    servings: 4,
    summary: 'Mixed mushrooms cooked down with tomato and rosemary, spooned over soft parmesan polenta.',
    ingredients: [
      { name: 'mixed mushrooms', amount: 1.5, unit: 'lb' },
      { name: 'tomato paste', amount: 2, unit: 'tbsp' },
      { name: 'rosemary sprigs', amount: 2, unit: '' },
      { name: 'polenta', amount: 1, unit: 'cup' },
      { name: 'parmesan', amount: 2, unit: 'oz' },
      { name: 'butter', amount: 3, unit: 'tbsp' },
      { name: 'garlic cloves', amount: 3, unit: '' },
    ],
    steps: [
      'Sear the mushrooms in batches until deeply browned; don’t crowd the pan.',
      'Add butter, garlic, rosemary, and tomato paste; cook until brick red, then splash in a cup of water and simmer 10 minutes.',
      'Meanwhile whisk the polenta into 4 cups simmering salted water; cook 25 minutes, then beat in parmesan.',
      'Serve the ragù over the polenta with more cheese.',
    ],
  },
  {
    id: 'house-sheetpan-sausage',
    title: 'Sheet-Pan Sausages with Potatoes & Peppers',
    categories: ['baked', 'roast', 'quick'],
    cuisine: 'American',
    diets: [],
    readyInMinutes: 40,
    servings: 4,
    summary: 'Everything on one pan: crisp-edged potatoes, blistered peppers, juicy sausages, mustard on the side.',
    ingredients: [
      { name: 'Italian sausages', amount: 6, unit: '' },
      { name: 'baby potatoes', amount: 1.5, unit: 'lb' },
      { name: 'bell peppers', amount: 2, unit: '' },
      { name: 'red onion', amount: 1, unit: '' },
      { name: 'olive oil', amount: 3, unit: 'tbsp' },
      { name: 'whole-grain mustard', amount: 2, unit: 'tbsp' },
    ],
    steps: [
      'Heat the oven to 450°F (230°C). Halve the potatoes and toss with oil and salt on a sheet pan; roast 15 minutes.',
      'Add the sausages and thick-sliced peppers and onion; roast 20 minutes more, turning once.',
      'Everything should be browned and sizzling. Serve with mustard.',
    ],
  },
  {
    id: 'house-baked-ziti',
    title: 'Weeknight Baked Ziti',
    categories: ['baked', 'pasta'],
    cuisine: 'Italian',
    diets: ['vegetarian'],
    readyInMinutes: 50,
    servings: 6,
    summary: 'Bubbling, golden-topped ziti with ricotta pockets — the dish rainy Tuesdays were invented for.',
    ingredients: [
      { name: 'ziti or penne', amount: 1, unit: 'lb' },
      { name: 'marinara sauce', amount: 32, unit: 'oz' },
      { name: 'ricotta', amount: 15, unit: 'oz' },
      { name: 'mozzarella', amount: 8, unit: 'oz' },
      { name: 'parmesan', amount: 2, unit: 'oz' },
      { name: 'basil leaves', amount: 1, unit: 'handful' },
    ],
    steps: [
      'Boil the pasta two minutes shy of al dente; drain.',
      'Toss with marinara, dollop in the ricotta, and fold once — leave streaks.',
      'Top with torn mozzarella and parmesan in a 9×13 dish.',
      'Bake at 425°F (220°C) for 20–25 minutes until browned and bubbling. Scatter with basil.',
    ],
  },
  {
    id: 'house-miso-salmon',
    title: 'Broiled Miso-Glazed Salmon with Rice',
    categories: ['quick', 'baked'],
    cuisine: 'Japanese',
    diets: ['pescatarian'],
    readyInMinutes: 25,
    servings: 4,
    summary: 'A five-ingredient glaze that blisters under the broiler; dinner in under half an hour.',
    ingredients: [
      { name: 'salmon fillets', amount: 4, unit: '' },
      { name: 'white miso', amount: 3, unit: 'tbsp' },
      { name: 'mirin', amount: 2, unit: 'tbsp' },
      { name: 'soy sauce', amount: 1, unit: 'tbsp' },
      { name: 'short-grain rice', amount: 1.5, unit: 'cups' },
      { name: 'scallions', amount: 3, unit: '' },
    ],
    steps: [
      'Start the rice.',
      'Whisk miso, mirin, and soy; coat the salmon and rest 10 minutes.',
      'Broil the fillets 6–8 minutes until the glaze chars in spots and the fish flakes.',
      'Serve over rice, showered with sliced scallions.',
    ],
  },
  {
    id: 'house-chicken-caesar',
    title: 'Grilled Chicken Caesar with Torn Croutons',
    categories: ['salad', 'grill'],
    cuisine: 'American',
    diets: [],
    readyInMinutes: 35,
    servings: 4,
    summary: 'Charred chicken thighs over crunchy romaine, olive-oil croutons torn rough so the dressing has somewhere to go.',
    ingredients: [
      { name: 'boneless chicken thighs', amount: 1.5, unit: 'lb' },
      { name: 'romaine hearts', amount: 3, unit: '' },
      { name: 'sourdough bread', amount: 0.5, unit: 'loaf' },
      { name: 'parmesan', amount: 2, unit: 'oz' },
      { name: 'mayonnaise', amount: 0.5, unit: 'cup' },
      { name: 'anchovy fillets', amount: 4, unit: '' },
      { name: 'lemon', amount: 1, unit: '' },
      { name: 'garlic cloves', amount: 2, unit: '' },
    ],
    steps: [
      'Whisk mayo with minced anchovy, garlic, lemon juice, and a handful of grated parmesan.',
      'Grill (or hard-sear) the seasoned thighs ~5 minutes a side; rest and slice.',
      'Tear the bread into ragged chunks, toss in olive oil, and toast until golden.',
      'Toss romaine with dressing and croutons; top with chicken and parmesan shavings.',
    ],
  },
  {
    id: 'house-smash-tacos',
    title: 'Smashed Carnitas-Style Tacos with Lime Slaw',
    categories: ['grill', 'quick'],
    cuisine: 'Mexican',
    diets: [],
    readyInMinutes: 30,
    servings: 4,
    summary: 'Crisped pork pressed onto tortillas on a hot griddle, cooled down with a sharp lime cabbage slaw.',
    ingredients: [
      { name: 'ground pork', amount: 1, unit: 'lb' },
      { name: 'corn tortillas', amount: 12, unit: '' },
      { name: 'green cabbage', amount: 0.5, unit: 'head' },
      { name: 'limes', amount: 3, unit: '' },
      { name: 'ground cumin', amount: 2, unit: 'tsp' },
      { name: 'dried oregano', amount: 1, unit: 'tsp' },
      { name: 'cilantro', amount: 1, unit: 'bunch' },
      { name: 'crema or sour cream', amount: 0.5, unit: 'cup' },
    ],
    steps: [
      'Season the pork with cumin, oregano, and salt.',
      'Shave the cabbage and toss with lime juice, salt, and half the cilantro.',
      'Press a thin layer of pork onto each tortilla; griddle pork-side down until crusty, flip to warm the tortilla.',
      'Top with slaw, crema, cilantro, and more lime.',
    ],
  },
  {
    id: 'house-cold-noodles',
    title: 'Cold Sesame Noodles with Cucumbers',
    categories: ['cold', 'quick', 'pasta'],
    cuisine: 'Chinese',
    diets: ['vegetarian'],
    readyInMinutes: 20,
    servings: 4,
    summary: 'Chilled noodles in a sesame-peanut sauce, smashed cucumbers, chili crisp on top. No oven, barely a stove.',
    ingredients: [
      { name: 'wheat noodles', amount: 1, unit: 'lb' },
      { name: 'peanut butter', amount: 3, unit: 'tbsp' },
      { name: 'toasted sesame oil', amount: 2, unit: 'tbsp' },
      { name: 'soy sauce', amount: 3, unit: 'tbsp' },
      { name: 'rice vinegar', amount: 2, unit: 'tbsp' },
      { name: 'cucumbers', amount: 2, unit: '' },
      { name: 'chili crisp', amount: 2, unit: 'tbsp' },
      { name: 'scallions', amount: 3, unit: '' },
    ],
    steps: [
      'Cook the noodles, rinse cold, and drain well.',
      'Whisk peanut butter, sesame oil, soy, vinegar, and a splash of water into a pourable sauce.',
      'Smack the cucumbers with the flat of a knife, tear into chunks, and salt briefly.',
      'Toss noodles in sauce; top with cucumbers, scallions, and chili crisp.',
    ],
  },
  {
    id: 'house-nicoise',
    title: 'Summer Niçoise with Jammy Eggs',
    categories: ['salad', 'cold'],
    cuisine: 'French',
    diets: ['pescatarian'],
    readyInMinutes: 35,
    servings: 4,
    summary: 'The hot-evening classic: olive-oil tuna, green beans, potatoes, olives, and 7-minute eggs on one big platter.',
    ingredients: [
      { name: 'olive-oil-packed tuna', amount: 10, unit: 'oz' },
      { name: 'baby potatoes', amount: 1, unit: 'lb' },
      { name: 'green beans', amount: 0.75, unit: 'lb' },
      { name: 'eggs', amount: 4, unit: '' },
      { name: 'niçoise olives', amount: 0.5, unit: 'cup' },
      { name: 'cherry tomatoes', amount: 1, unit: 'pint' },
      { name: 'dijon mustard', amount: 1, unit: 'tbsp' },
      { name: 'red wine vinegar', amount: 2, unit: 'tbsp' },
      { name: 'olive oil', amount: 0.33, unit: 'cup' },
    ],
    steps: [
      'Boil the potatoes until tender; blanch the beans in the same pot for the last 3 minutes.',
      'Cook the eggs 7 minutes, then shock in ice water and halve.',
      'Whisk mustard, vinegar, and oil into a sharp vinaigrette.',
      'Arrange everything on a platter, dress generously, and season the tomatoes and eggs with flaky salt.',
    ],
  },
  {
    id: 'house-grilled-halloumi',
    title: 'Grilled Halloumi & Peach Salad',
    categories: ['grill', 'salad'],
    cuisine: 'Mediterranean',
    diets: ['vegetarian'],
    readyInMinutes: 25,
    servings: 4,
    summary: 'Squeaky grilled cheese, charred peaches, arugula, and a honey-lime drizzle — peak hot-evening food.',
    ingredients: [
      { name: 'halloumi', amount: 16, unit: 'oz' },
      { name: 'ripe peaches', amount: 3, unit: '' },
      { name: 'arugula', amount: 5, unit: 'oz' },
      { name: 'honey', amount: 2, unit: 'tbsp' },
      { name: 'limes', amount: 2, unit: '' },
      { name: 'olive oil', amount: 3, unit: 'tbsp' },
      { name: 'mint leaves', amount: 1, unit: 'handful' },
    ],
    steps: [
      'Slice halloumi and peaches; brush with oil.',
      'Grill both until well-marked — cheese ~2 minutes a side, peaches until softened.',
      'Whisk honey, lime juice, and olive oil.',
      'Pile arugula on a platter, top with halloumi and peaches, drizzle, and finish with torn mint.',
    ],
  },
  {
    id: 'house-lemon-orzo',
    title: 'One-Pot Lemon Orzo with Shrimp & Feta',
    categories: ['pasta', 'quick'],
    cuisine: 'Greek',
    diets: ['pescatarian'],
    readyInMinutes: 30,
    servings: 4,
    summary: 'Orzo cooked risotto-style, shrimp folded in at the end, briny feta over the top.',
    ingredients: [
      { name: 'orzo', amount: 1, unit: 'lb' },
      { name: 'shrimp', amount: 1, unit: 'lb' },
      { name: 'feta', amount: 4, unit: 'oz' },
      { name: 'lemons', amount: 2, unit: '' },
      { name: 'chicken stock', amount: 4, unit: 'cups' },
      { name: 'garlic cloves', amount: 4, unit: '' },
      { name: 'baby spinach', amount: 5, unit: 'oz' },
      { name: 'olive oil', amount: 3, unit: 'tbsp' },
    ],
    steps: [
      'Toast the orzo in olive oil with the garlic until golden and nutty.',
      'Add stock a cup at a time, stirring, until the orzo is creamy and just tender, ~12 minutes.',
      'Fold in shrimp and spinach; cook 3 minutes until the shrimp curl pink.',
      'Off heat, add lemon zest and juice; crumble feta over.',
    ],
  },
  {
    id: 'house-roast-chicken',
    title: 'Sunday Roast Chicken with Pan Vegetables',
    categories: ['roast', 'baked'],
    cuisine: 'American',
    diets: [],
    readyInMinutes: 90,
    servings: 4,
    summary: 'A dry-brined bird over carrots and onions that catch all the drippings. Leftovers are the plan, not the accident.',
    ingredients: [
      { name: 'whole chicken', amount: 1, unit: '' },
      { name: 'carrots', amount: 1, unit: 'lb' },
      { name: 'yellow onions', amount: 2, unit: '' },
      { name: 'butter', amount: 3, unit: 'tbsp' },
      { name: 'thyme sprigs', amount: 6, unit: '' },
      { name: 'lemon', amount: 1, unit: '' },
    ],
    steps: [
      'Salt the chicken all over (the night before if you can; an hour ahead if not).',
      'Set it on thick-cut carrots and onions in a skillet; rub with soft butter, stuff with lemon and thyme.',
      'Roast at 425°F (220°C) for 50–60 minutes to 155°F in the breast.',
      'Rest 15 minutes; carve over the pan vegetables.',
    ],
  },
  {
    id: 'house-dal',
    title: 'Red Lentil Dal with Garlic Tarka',
    categories: ['stew', 'soup', 'quick'],
    cuisine: 'Indian',
    diets: ['vegan', 'vegetarian'],
    readyInMinutes: 40,
    servings: 4,
    summary: 'Pantry dinner royalty: creamy spiced lentils finished with sizzled garlic, cumin seed, and chili.',
    ingredients: [
      { name: 'red lentils', amount: 1.5, unit: 'cups' },
      { name: 'coconut milk', amount: 1, unit: 'can' },
      { name: 'ground turmeric', amount: 1, unit: 'tsp' },
      { name: 'cumin seeds', amount: 2, unit: 'tsp' },
      { name: 'garlic cloves', amount: 6, unit: '' },
      { name: 'ginger', amount: 2, unit: 'inches' },
      { name: 'neutral oil', amount: 3, unit: 'tbsp' },
      { name: 'basmati rice', amount: 1.5, unit: 'cups' },
      { name: 'red chili flakes', amount: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Simmer lentils with turmeric, grated ginger, and 4 cups water until collapsed, ~25 minutes; stir in coconut milk and salt.',
      'Cook the rice.',
      'Sizzle sliced garlic, cumin seeds, and chili flakes in hot oil until the garlic just turns gold.',
      'Pour the tarka over the dal at the table — the hiss is the point.',
    ],
  },
  {
    id: 'house-french-onion-pasta',
    title: 'French Onion Baked Rigatoni',
    categories: ['baked', 'pasta', 'braise'],
    cuisine: 'French',
    diets: ['vegetarian'],
    readyInMinutes: 65,
    servings: 6,
    summary: 'Deeply caramelized onions folded through rigatoni with gruyère, baked until the top goes bistro-crock crusty.',
    ingredients: [
      { name: 'yellow onions', amount: 3, unit: 'lb' },
      { name: 'rigatoni', amount: 1, unit: 'lb' },
      { name: 'gruyère', amount: 8, unit: 'oz' },
      { name: 'butter', amount: 4, unit: 'tbsp' },
      { name: 'beef or vegetable stock', amount: 1.5, unit: 'cups' },
      { name: 'sherry or white wine', amount: 0.33, unit: 'cup' },
      { name: 'thyme sprigs', amount: 4, unit: '' },
    ],
    steps: [
      'Slice the onions and cook in butter with thyme, stirring now and then, 35–40 minutes to deep mahogany.',
      'Deglaze with sherry; add stock and simmer briefly.',
      'Boil the rigatoni 3 minutes shy; fold into the onions with half the gruyère.',
      'Top with the rest and bake at 450°F (230°C) until browned, ~15 minutes.',
    ],
  },
  {
    id: 'house-burgers',
    title: 'Backyard Smash Burgers',
    categories: ['grill', 'quick'],
    cuisine: 'American',
    diets: [],
    readyInMinutes: 25,
    servings: 4,
    summary: 'Thin patties with lacy edges, toasted buns, and a proper burger sauce. Best eaten outside.',
    ingredients: [
      { name: 'ground beef (80/20)', amount: 1.5, unit: 'lb' },
      { name: 'burger buns', amount: 4, unit: '' },
      { name: 'American cheese', amount: 4, unit: 'slices' },
      { name: 'mayonnaise', amount: 0.25, unit: 'cup' },
      { name: 'dill pickles', amount: 4, unit: '' },
      { name: 'ketchup', amount: 2, unit: 'tbsp' },
      { name: 'iceberg lettuce', amount: 0.5, unit: 'head' },
    ],
    steps: [
      'Stir mayo, ketchup, and minced pickle into a sauce.',
      'Divide beef into 8 loose balls; smash flat on a ripping-hot griddle and season hard.',
      'Flip when the edges lace, add cheese, and stack in pairs.',
      'Toast the buns in the fat; build with sauce and lettuce.',
    ],
  },
  {
    id: 'house-gazpacho',
    title: 'Gazpacho with Torn Bread & Jamón',
    categories: ['cold', 'soup'],
    cuisine: 'Spanish',
    diets: [],
    readyInMinutes: 20,
    servings: 4,
    summary: 'Blender-cold tomato soup for the hottest nights — no stove touched. Skip the jamón to make it vegan.',
    ingredients: [
      { name: 'ripe tomatoes', amount: 2.5, unit: 'lb' },
      { name: 'cucumber', amount: 1, unit: '' },
      { name: 'green bell pepper', amount: 1, unit: '' },
      { name: 'stale bread', amount: 2, unit: 'slices' },
      { name: 'sherry vinegar', amount: 2, unit: 'tbsp' },
      { name: 'olive oil', amount: 0.5, unit: 'cup' },
      { name: 'jamón or prosciutto', amount: 2, unit: 'oz' },
    ],
    steps: [
      'Blend tomatoes, cucumber, pepper, soaked bread, vinegar, and salt until completely smooth.',
      'With the motor running, stream in the olive oil until the soup turns pale and creamy.',
      'Chill at least 2 hours (or blend in a few ice cubes).',
      'Serve very cold, topped with torn jamón, diced cucumber, and more oil.',
    ],
  },
]

/** Category → the short label shown on chips. */
export const CATEGORY_LABELS = {
  soup: 'soup',
  stew: 'stew',
  braise: 'braise',
  baked: 'baked',
  roast: 'roast',
  pasta: 'pasta',
  grill: 'grill',
  salad: 'salad',
  cold: 'cold prep',
  quick: 'quick',
}

/** Shown on chips for meals but not offered as a tag when editing recipes. */
export const EXTRA_LABELS = { takeout: 'takeout' }
